/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Alexander Batista
 */
public class GUI extends javax.swing.JFrame {

    boolean integrar;
    String dato = "";
    int cont;
    public static ArrayList[] Historial;
    DefaultTableModel ModeloHistorial = new DefaultTableModel();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        estado(false);
        Historial = new ArrayList[10];
        cont = 9;
        ModeloHistorial.addColumn("Función");
        ModeloHistorial.addColumn("Resultado");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdalHistorial = new javax.swing.JDialog();
        jbtnMostrar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlitHistorial = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxpFuncion = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxpProcedimiento = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jbtnIntegrando = new javax.swing.JButton();
        jbtnCuadrado = new javax.swing.JButton();
        jbtnCubo = new javax.swing.JButton();
        jbtnPotencia = new javax.swing.JButton();
        jbtnExponencial = new javax.swing.JButton();
        jbtnParentecisA = new javax.swing.JButton();
        jbtnParentecisC = new javax.swing.JButton();
        jbtnCosiente = new javax.swing.JButton();
        jbtnProducto = new javax.swing.JButton();
        jbtnDerivada = new javax.swing.JButton();
        jbtnSeno = new javax.swing.JButton();
        jbtnCoseno = new javax.swing.JButton();
        jbtnTangente = new javax.swing.JButton();
        jbtnCotangente = new javax.swing.JButton();
        jbtnSecante = new javax.swing.JButton();
        jbtnCosecante = new javax.swing.JButton();
        jbtnLogaritmoNatural = new javax.swing.JButton();
        jbtnValorAbsoluto = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxpResultado = new javax.swing.JTextPane();
        jbtnComentario = new javax.swing.JButton();
        jbtnHistorial = new javax.swing.JButton();
        jbtnImprimir = new javax.swing.JButton();

        jdalHistorial.setTitle("Historial de Resultados");

        jbtnMostrar.setText("Mostrar");
        jbtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarActionPerformed(evt);
            }
        });

        jlitHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jlitHistorial);

        javax.swing.GroupLayout jdalHistorialLayout = new javax.swing.GroupLayout(jdalHistorial.getContentPane());
        jdalHistorial.getContentPane().setLayout(jdalHistorialLayout);
        jdalHistorialLayout.setHorizontalGroup(
            jdalHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdalHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdalHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdalHistorialLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnMostrar)))
                .addContainerGap())
        );
        jdalHistorialLayout.setVerticalGroup(
            jdalHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdalHistorialLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jbtnMostrar)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CDI");
        setBackground(new java.awt.Color(102, 255, 204));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Función:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jScrollPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jtxpFuncion.setBorder(null);
        jtxpFuncion.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jtxpFuncion.setEnabled(false);
        jtxpFuncion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxpFuncionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxpFuncionKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtxpFuncion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Procedimiento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel3.setOpaque(false);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtxpProcedimiento.setEditable(false);
        jScrollPane2.setViewportView(jtxpProcedimiento);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operadores:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jbtnIntegrando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnIntegrando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/integrando.png"))); // NOI18N
        jbtnIntegrando.setToolTipText("Integrando");
        jbtnIntegrando.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnIntegrando.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnIntegrando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIntegrandoActionPerformed(evt);
            }
        });

        jbtnCuadrado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cuadrado.png"))); // NOI18N
        jbtnCuadrado.setToolTipText("Potencia Cuadrado");
        jbtnCuadrado.setEnabled(false);
        jbtnCuadrado.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCuadrado.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuadradoActionPerformed(evt);
            }
        });

        jbtnCubo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cubo.png"))); // NOI18N
        jbtnCubo.setToolTipText("Potencia Cubo");
        jbtnCubo.setEnabled(false);
        jbtnCubo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCubo.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCubo.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCubo.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCuboActionPerformed(evt);
            }
        });

        jbtnPotencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/potencia.png"))); // NOI18N
        jbtnPotencia.setToolTipText("Potencia n");
        jbtnPotencia.setEnabled(false);
        jbtnPotencia.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnPotencia.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPotenciaActionPerformed(evt);
            }
        });

        jbtnExponencial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnExponencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exponencial.png"))); // NOI18N
        jbtnExponencial.setToolTipText("Función Exponencial");
        jbtnExponencial.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnExponencial.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExponencialActionPerformed(evt);
            }
        });

        jbtnParentecisA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnParentecisA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ParentecisA.png"))); // NOI18N
        jbtnParentecisA.setToolTipText("Paréntecia Abierto");
        jbtnParentecisA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnParentecisA.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnParentecisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParentecisAActionPerformed(evt);
            }
        });

        jbtnParentecisC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnParentecisC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ParentecisC.png"))); // NOI18N
        jbtnParentecisC.setToolTipText("Paréntecia Cerrado");
        jbtnParentecisC.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnParentecisC.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnParentecisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParentecisCActionPerformed(evt);
            }
        });

        jbtnCosiente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCosiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cosiente.png"))); // NOI18N
        jbtnCosiente.setToolTipText("Cosiente");
        jbtnCosiente.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCosiente.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCosiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosienteActionPerformed(evt);
            }
        });

        jbtnProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/producto.png"))); // NOI18N
        jbtnProducto.setToolTipText("Producto");
        jbtnProducto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnProducto.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnProducto.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnProducto.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductoActionPerformed(evt);
            }
        });

        jbtnDerivada.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnDerivada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Derivacion.png"))); // NOI18N
        jbtnDerivada.setToolTipText("Derivada");
        jbtnDerivada.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnDerivada.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDerivadaActionPerformed(evt);
            }
        });

        jbtnSeno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnSeno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Seno.png"))); // NOI18N
        jbtnSeno.setToolTipText("Seno");
        jbtnSeno.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnSeno.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnSeno.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnSeno.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSenoActionPerformed(evt);
            }
        });

        jbtnCoseno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCoseno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Coseno.png"))); // NOI18N
        jbtnCoseno.setToolTipText("Coseno");
        jbtnCoseno.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCoseno.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCoseno.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCoseno.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosenoActionPerformed(evt);
            }
        });

        jbtnTangente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnTangente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Tangente.png"))); // NOI18N
        jbtnTangente.setToolTipText("Tangente");
        jbtnTangente.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnTangente.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnTangente.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnTangente.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTangenteActionPerformed(evt);
            }
        });

        jbtnCotangente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCotangente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cotangente.png"))); // NOI18N
        jbtnCotangente.setToolTipText("Cotangente");
        jbtnCotangente.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCotangente.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCotangente.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCotangente.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCotangenteActionPerformed(evt);
            }
        });

        jbtnSecante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnSecante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Secante.png"))); // NOI18N
        jbtnSecante.setToolTipText("Secante");
        jbtnSecante.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnSecante.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnSecante.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnSecante.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSecanteActionPerformed(evt);
            }
        });

        jbtnCosecante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnCosecante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cosecante.png"))); // NOI18N
        jbtnCosecante.setToolTipText("Cosecante");
        jbtnCosecante.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCosecante.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnCosecante.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnCosecante.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnCosecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosecanteActionPerformed(evt);
            }
        });

        jbtnLogaritmoNatural.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnLogaritmoNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Logaritmo_Natural.png"))); // NOI18N
        jbtnLogaritmoNatural.setToolTipText("Logaritmo Natural.");
        jbtnLogaritmoNatural.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnLogaritmoNatural.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnLogaritmoNatural.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnLogaritmoNatural.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnLogaritmoNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogaritmoNaturalActionPerformed(evt);
            }
        });

        jbtnValorAbsoluto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnValorAbsoluto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Valor_Absoluto.png"))); // NOI18N
        jbtnValorAbsoluto.setToolTipText("Valor Absoluto");
        jbtnValorAbsoluto.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnValorAbsoluto.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnValorAbsoluto.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnValorAbsoluto.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnValorAbsoluto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnValorAbsolutoActionPerformed(evt);
            }
        });

        jbtnIgual.setBackground(new java.awt.Color(102, 255, 102));
        jbtnIgual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnIgual.setText("=");
        jbtnIgual.setToolTipText("Iguall");
        jbtnIgual.setAlignmentY(0.0F);
        jbtnIgual.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtnIgual.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnIgual.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnIgual.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });

        jbtnNuevo.setBackground(new java.awt.Color(255, 0, 0));
        jbtnNuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnNuevo.setText("N");
        jbtnNuevo.setToolTipText("Nuevo");
        jbtnNuevo.setAlignmentY(0.0F);
        jbtnNuevo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtnNuevo.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnNuevo.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnNuevo.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnIntegrando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnParentecisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnParentecisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCosiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCotangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnCosecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnLogaritmoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnIntegrando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCubo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnParentecisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnParentecisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCosiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCotangente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCosecante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnLogaritmoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnValorAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setToolTipText("");

        jtxpResultado.setEditable(false);
        jtxpResultado.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jScrollPane1.setViewportView(jtxpResultado);

        jbtnComentario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnComentario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Descripción.png"))); // NOI18N
        jbtnComentario.setToolTipText("Descripción del Resultado");
        jbtnComentario.setEnabled(false);
        jbtnComentario.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnComentario.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnComentario.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnComentario.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnComentarioActionPerformed(evt);
            }
        });

        jbtnHistorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historial.png"))); // NOI18N
        jbtnHistorial.setToolTipText("Historial");
        jbtnHistorial.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnHistorial.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnHistorial.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnHistorial.setOpaque(false);
        jbtnHistorial.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHistorialActionPerformed(evt);
            }
        });

        jbtnImprimir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/impresora.png"))); // NOI18N
        jbtnImprimir.setToolTipText("Imprimir");
        jbtnImprimir.setDoubleBuffered(true);
        jbtnImprimir.setEnabled(false);
        jbtnImprimir.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnImprimir.setMaximumSize(new java.awt.Dimension(25, 25));
        jbtnImprimir.setMinimumSize(new java.awt.Dimension(25, 25));
        jbtnImprimir.setPreferredSize(new java.awt.Dimension(25, 25));
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbtnComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(297, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        Border borde = new TitledBorder("");
        this.jPanel5.setBorder(borde);
        this.jtxpFuncion.setEnabled(false);
        this.jtxpFuncion.setText("");
        this.jtxpResultado.setText("");
        this.jtxpProcedimiento.setText("");
        integrar = false;
        this.jtxpFuncion.grabFocus();
        estado(false);
        CDI.Comentario.clear();
        this.jbtnIntegrando.setEnabled(true);
        this.jbtnDerivada.setEnabled(true);
        this.jbtnImprimir.setEnabled(false);
        this.jbtnComentario.setEnabled(false);
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        if (!"".equals(this.jtxpFuncion.getText())) {
            this.jbtnImprimir.setEnabled(true);
            this.jbtnComentario.setEnabled(true);
            String op, cad;
            int pos = 0;
            ArrayList resultados = new ArrayList();
            if (!integrar) {
                op = "D";
            } else {
                op = "I";
            }
            cad = this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("(") + 1, this.jtxpFuncion.getText().lastIndexOf(")"));
            if (!"".equals(cad)) {
                CDI.CDIMaster(cad, op, dato);
                resultados=Segmentador.Retorno;
            } else if (integrar) {
                CDI.CDIMaster("1", op, dato);
                resultados=Segmentador.Retorno;
            } else {
                JOptionPane.showMessageDialog(this, "Para derivar debe colocar al menos un numero diferente de 0", "Error", JOptionPane.ERROR_MESSAGE);
                this.jtxpFuncion.grabFocus();
                if (!integrar) {
                    this.jtxpFuncion.setCaretPosition(7);
                }
            }
            this.jtxpProcedimiento.setText("");
            if (resultados != null) {
                for (int i = 0; i < resultados.size(); i++) {
                    if (resultados.get(i).toString().equals("&&&")) {
                        pos = i;
                        break;
                    }
                }
                for (int i = 0; i < pos; i++) {
                    this.jtxpProcedimiento.setText(this.jtxpProcedimiento.getText().concat(resultados.get(i).toString()));
                    changeLineSpacing(Float.valueOf("1"), false, this.jtxpProcedimiento);
                }
                pos++;
                for (int i = pos; i < resultados.size(); i++) {
                    this.jtxpResultado.setText(this.jtxpResultado.getText().concat(resultados.get(i).toString()));
                    changeLineSpacing(Float.valueOf("-0.5"), false, this.jtxpResultado);
                }
                resultados.clear();
                GuardarHistorial();
            } else {
                JOptionPane.showMessageDialog(this, "Debe Introducir una función válida para el sistema. /n Revise su función e intente de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe Introducir una función antes de dar clic a este botón. /n Intente de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnValorAbsolutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnValorAbsolutoActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat(arregloParentecis(false)).concat(Select2()));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnValorAbsolutoActionPerformed

    private void jbtnLogaritmoNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogaritmoNaturalActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("ln".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 3);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLogaritmoNaturalActionPerformed

    private void jbtnCosecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosecanteActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Csc".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCosecanteActionPerformed

    private void jbtnSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSecanteActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Sec".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSecanteActionPerformed

    private void jbtnCotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCotangenteActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Cot".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCotangenteActionPerformed

    private void jbtnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTangenteActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Tan".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnTangenteActionPerformed

    private void jbtnCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosenoActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Cos".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCosenoActionPerformed

    private void jbtnSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSenoActionPerformed
        String sel = Select(false);
        this.jtxpFuncion.setText(sel.concat("Sen".concat(arregloParentecis(true)).concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 4);
    }//GEN-LAST:event_jbtnSenoActionPerformed

    private void jbtnDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDerivadaActionPerformed
        LeerDiferencial();
        if (dato != null) {
            Border borde = new TitledBorder("Al Derivar resulta:");
            if (!"".equals(dato)) {
                this.jtxpFuncion.setText(this.jtxpFuncion.getText().concat(" d".concat(" \n──".concat("()\nd".concat(String.valueOf(dato.charAt(0)))))));
                integrar = false;
                this.jPanel5.setBorder(borde);
                this.jtxpFuncion.setEnabled(true);
                changeLineSpacing(Float.valueOf("-0.5"), false, this.jtxpFuncion);
                this.jbtnIntegrando.setEnabled(false);
                this.jbtnDerivada.setEnabled(false);
                this.jtxpFuncion.grabFocus();
                this.jtxpFuncion.setCaretPosition(7);
                estado(true);
            }
        }
    }//GEN-LAST:event_jbtnDerivadaActionPerformed

    private void jbtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductoActionPerformed
        Parentesis(this.jtxpFuncion.getText(), false);
    }//GEN-LAST:event_jbtnProductoActionPerformed

    private void jbtnCosienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosienteActionPerformed
        Parentesis(this.jtxpFuncion.getText(), true);
    }//GEN-LAST:event_jbtnCosienteActionPerformed

    private void jbtnParentecisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParentecisCActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat(")".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnParentecisCActionPerformed

    private void jbtnParentecisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParentecisAActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat("()".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnParentecisAActionPerformed

    private void jbtnExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExponencialActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat("e".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnExponencialActionPerformed

    private void jbtnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPotenciaActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat("^".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 1);
    }//GEN-LAST:event_jbtnPotenciaActionPerformed

    private void jbtnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuboActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat("^3".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 2);
    }//GEN-LAST:event_jbtnCuboActionPerformed

    private void jbtnCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCuadradoActionPerformed
        String sel = Select(true);
        this.jtxpFuncion.setText(sel.concat("^2".concat(Select2())));
        this.jtxpFuncion.grabFocus();
        this.jtxpFuncion.setCaretPosition(sel.length() + 2);
    }//GEN-LAST:event_jbtnCuadradoActionPerformed

    private void jbtnIntegrandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIntegrandoActionPerformed
        LeerDiferencial();
        if (dato != null) {
            Border borde = new TitledBorder("Al integrar resulta:");
            String dat = String.valueOf(dato.charAt(0));
            try {
                if (dat.hashCode() >= 0) {
                    this.jtxpFuncion.setText("∫()d".concat(String.valueOf(dato.charAt(0)).concat(" ")));
                    this.jPanel5.setBorder(borde);
                    integrar = true;
                    this.jtxpFuncion.setEnabled(true);
                    this.jtxpFuncion.setCaretPosition(2);
                    this.jtxpFuncion.grabFocus();
                    this.jbtnDerivada.setEnabled(false);
                    this.jbtnIntegrando.setEnabled(false);
                    estado(true);
                    this.jbtnLogaritmoNatural.setEnabled(false);
                } else {
                }
            } catch (NullPointerException n) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una letra", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnIntegrandoActionPerformed

    private void jtxpFuncionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxpFuncionKeyReleased

    }//GEN-LAST:event_jtxpFuncionKeyReleased

    private void jtxpFuncionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxpFuncionKeyPressed
        boolean Potencia = true;
        jtxasetFont(this.jtxpFuncion);
        int pos = 0;
        char caracter = evt.getKeyChar();
        if (this.jtxpFuncion.getText().equals("")) {
            this.jbtnDerivada.setEnabled(true);
            this.jbtnIntegrando.setEnabled(true);
        }
        if (evt.getKeyCode() == 127 || evt.getKeyCode() == 8) {
            if (!integrar) {
                if (this.jtxpFuncion.getCaretPosition() == 7) {
                    this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, 7).concat(" ").concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getCaretPosition(), this.jtxpFuncion.getText().length())));
                    this.jtxpFuncion.setCaretPosition(8);
                }
                if (this.jtxpFuncion.getCaretPosition() == this.jtxpFuncion.getText().lastIndexOf(")")) {
                    int p = this.jtxpFuncion.getCaretPosition();
                    this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, p).concat(" ").concat(this.jtxpFuncion.getText().substring(p, this.jtxpFuncion.getText().length())));
                    this.jtxpFuncion.setCaretPosition(p);
                }
            } else {
                if (this.jtxpFuncion.getCaretPosition() == 2) {
                    this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, 2).concat(" ").concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getCaretPosition(), this.jtxpFuncion.getText().length())));
                    this.jtxpFuncion.setCaretPosition(8);
                }
                if (this.jtxpFuncion.getCaretPosition() == this.jtxpFuncion.getText().lastIndexOf(")")) {
                    int p = this.jtxpFuncion.getCaretPosition();
                    this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, p).concat(" ").concat(this.jtxpFuncion.getText().substring(p, this.jtxpFuncion.getText().length())));
                    this.jtxpFuncion.setCaretPosition(p);
                }
            }
        }
        if (Character.isLetter(caracter)) {
            if (!String.valueOf(evt.getKeyChar()).equals(dato)) {
                if (JOptionPane.showConfirmDialog(this, "Debe ingresar la misma letra del diferencial \n ¿Deséas Continuar?", "Información", 1) == 1) {
                    int Position = this.jtxpFuncion.getCaretPosition();
                    this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, Position - 1).concat(this.jtxpFuncion.getText().substring(Position, this.jtxpFuncion.getText().length())));
                    jtxasetFont(this.jtxpFuncion);
                    this.jtxpFuncion.grabFocus();
                    this.jtxpFuncion.setCaretPosition(Position - 1);
                    this.jbtnCuadrado.setEnabled(false);
                    this.jbtnCubo.setEnabled(false);
                    this.jbtnPotencia.setEnabled(false);
                }
            } else {
                this.jbtnCuadrado.setEnabled(true);
                this.jbtnCubo.setEnabled(true);
                this.jbtnPotencia.setEnabled(true);
            }
        } else {
            this.jbtnCuadrado.setEnabled(false);
            this.jbtnCubo.setEnabled(false);
            this.jbtnPotencia.setEnabled(false);
        }
        if (evt.getKeyChar() == '^') {
            Potencia = true;
        } else if (evt.getKeyChar() == '+' || evt.getKeyChar() == '-' || evt.getKeyChar() == '(' 
                || ((evt.getKeyCode() >= 97 && evt.getKeyCode() <= 122) 
                || (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90))) {
            Potencia = false;
        } else if (Potencia) {
            System.out.println("no se acepta letra");
        }
        if (Potencia) {
            System.out.println("hola");
        }

    }//GEN-LAST:event_jtxpFuncionKeyPressed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        FileWriter fichero;
        String Nombre = "";
        try {
            Nombre = getSaltString();
            fichero = new FileWriter("c:/Resultados/" + Nombre + ".doc");
            fichero.write(this.jtxpFuncion.getText());
            fichero.write("\n");
            fichero.write(this.jtxpProcedimiento.getText());
            fichero.write("\n");
            fichero.write("Resultado: ");
            fichero.write("\n");
            fichero.write(this.jtxpResultado.getText());
            fichero.write("\n");
            fichero.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el Archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        try {
            Runtime obj = Runtime.getRuntime();
            //La instrucción es notepad para abrir el bloc de notas, espacio
            //y la ruta donde esta el archivo
            obj.exec("cmd /c start notepad " + "\"c:/Resultados/" + Nombre + ".doc\"");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Este archivo no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void jbtnComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnComentarioActionPerformed
        String Texto = "";

        for (int i = 0; i < CDI.Comentario.size(); i++) {
            for (int j = 1; j < CDI.Comentario.size(); j++) {
                if (CDI.Comentario.get(i).equals(CDI.Comentario.get(j)) && j != i) {
                    CDI.Comentario.set(j, "$$$");
                }
            }
        }
        for (Object Descripcion : CDI.Comentario) {
            if (!"$$$".equals(Descripcion.toString())) {
                Texto = Texto.concat(Descripcion.toString()).concat("\n");
            }
        }
        JOptionPane.showMessageDialog(this, "En esta función se aplicó lo siguiente: \n" + Texto, "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnComentarioActionPerformed

    private void jbtnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistorialActionPerformed
        int contador = 0;
        Vector Datos = new Vector();
        for (int i = 0; i < ModeloHistorial.getRowCount(); i++) {
            ModeloHistorial.removeRow(i);
        }
        if (Historial[9]!=null) {
            for (ArrayList Historial1 : Historial) {
                if (Historial1 != null) {
                    Datos.add(Historial1.get(0).toString());
                    Datos.add(Historial1.get(4).toString());
                    ModeloHistorial.addRow(Datos);
                    contador++;
                }
            }
            this.jlitHistorial.setModel(ModeloHistorial);
            CentrarVentana(jdalHistorial);
        } else {
            JOptionPane.showMessageDialog(this, "No hay operaciones guardadas.\nDebe de resolver al menos una (1)", "Información", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jbtnHistorialActionPerformed

    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
        if (this.jlitHistorial.getSelectedRows().length!=0) {
            String seleccion = this.jlitHistorial.getValueAt(0,this.jlitHistorial.getSelectedRow()).toString();
            System.out.println(seleccion);
            ArrayList lista = new ArrayList();
            for (int i = 9; i > 0; i--) {
                lista = Historial[i];
                if (lista.get(0) == seleccion) {
                    break;
                }
            }
            this.jtxpFuncion.setText(lista.get(0).toString());
            this.jtxpProcedimiento.setText(lista.get(2).toString());
            this.jtxpResultado.setText(lista.get(4).toString());
            this.jdalHistorial.setVisible(false);
            CDI.Comentario.clear();
            for (int i = 6; i < lista.size(); i++) {
                CDI.Comentario.add(lista.get(i));
            }
            estado(true);
            this.jbtnComentario.setEnabled(true);
            this.jbtnImprimir.setEnabled(true);
            this.jbtnIntegrando.setEnabled(false);
            this.jbtnDerivada.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un ejercicio antes de mostrarlo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbtnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnComentario;
    private javax.swing.JButton jbtnCosecante;
    private javax.swing.JButton jbtnCoseno;
    private javax.swing.JButton jbtnCosiente;
    private javax.swing.JButton jbtnCotangente;
    private javax.swing.JButton jbtnCuadrado;
    private javax.swing.JButton jbtnCubo;
    private javax.swing.JButton jbtnDerivada;
    private javax.swing.JButton jbtnExponencial;
    private javax.swing.JButton jbtnHistorial;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JButton jbtnIntegrando;
    private javax.swing.JButton jbtnLogaritmoNatural;
    private javax.swing.JButton jbtnMostrar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnParentecisA;
    private javax.swing.JButton jbtnParentecisC;
    private javax.swing.JButton jbtnPotencia;
    private javax.swing.JButton jbtnProducto;
    private javax.swing.JButton jbtnSecante;
    private javax.swing.JButton jbtnSeno;
    private javax.swing.JButton jbtnTangente;
    private javax.swing.JButton jbtnValorAbsoluto;
    private javax.swing.JDialog jdalHistorial;
    private javax.swing.JTable jlitHistorial;
    private javax.swing.JTextPane jtxpFuncion;
    private javax.swing.JTextPane jtxpProcedimiento;
    private javax.swing.JTextPane jtxpResultado;
    // End of variables declaration//GEN-END:variables

    private String Select(boolean tipo) {
        if (tipo) {
            return this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getCaretPosition());
        } else {
            return this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getText().indexOf("(") + 1);
        }
    }

    private String Select2() {
        return this.jtxpFuncion.getText().substring(this.jtxpFuncion.getCaretPosition(), this.jtxpFuncion.getText().length());
    }

    public String getSaltString() {
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 18) { // length of the random string.
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;
    }

    private void changeLineSpacing(float factor, boolean replace, JTextPane jtxpvariable) {
        jtxpvariable.selectAll();
        MutableAttributeSet set = new SimpleAttributeSet(jtxpvariable.getParagraphAttributes());
        StyleConstants.setLineSpacing(set, factor);
        jtxpvariable.setParagraphAttributes(set, replace);
        jtxasetFont(jtxpvariable);
    }

    private void jtxasetFont(JTextPane jtxpvariable) {
        Font fuente = new Font("Times New Roman", Font.ITALIC, 18);
        jtxpvariable.setFont(fuente);
    }

    public String arregloParentecis(boolean Prentesis) {
        String cadena;
        if (Prentesis) {
            cadena = "(".concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("(") + 1, this.jtxpFuncion.getText().lastIndexOf(")"))).concat(")");
            return cadena;
        } else {
            cadena = "|".concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("(") + 1, this.jtxpFuncion.getText().lastIndexOf(")"))).concat("|");
            return cadena;
        }
    }

    private void estado(boolean b) {
        this.jbtnCosecante.setEnabled(b);
        this.jbtnCoseno.setEnabled(b);
        this.jbtnCosiente.setEnabled(b);
        this.jbtnCotangente.setEnabled(b);
        this.jbtnCuadrado.setEnabled(b);
        this.jbtnCubo.setEnabled(b);
        this.jbtnExponencial.setEnabled(b);
        this.jbtnIgual.setEnabled(b);
        this.jbtnLogaritmoNatural.setEnabled(b);
        this.jbtnNuevo.setEnabled(b);
        this.jbtnParentecisA.setEnabled(b);
        this.jbtnParentecisC.setEnabled(b);
        this.jbtnPotencia.setEnabled(b);
        this.jbtnProducto.setEnabled(b);
        this.jbtnSecante.setEnabled(b);
        this.jbtnSeno.setEnabled(b);
        this.jbtnTangente.setEnabled(b);
        this.jbtnValorAbsoluto.setEnabled(b);
    }

    private void Parentesis(String texto, boolean Cosiente) {
        String sel = Select(true);
        String sel2 = Select2();
        boolean bol = true;
        boolean parentesis = false;
        for (int i = 0; i < sel.length(); i++) {
            parentesis = sel.charAt(i) == '(';
        }
        if (parentesis) {
            if (!Cosiente) {
                this.jtxpFuncion.setText(sel.concat("()()").concat(sel2));
            } else {
                this.jtxpFuncion.setText(sel.concat("()/()").concat(sel2));
            }
            this.jtxpFuncion.grabFocus();
            this.jtxpFuncion.setCaretPosition(sel.length() + 1);
        } else {
            if (!Cosiente) {
                this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getText().indexOf("(")).concat("(").concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("("), this.jtxpFuncion.getCaretPosition())).concat(")").concat("()").concat(sel2));
                this.jtxpFuncion.grabFocus();
                this.jtxpFuncion.setCaretPosition(sel.length() + 3);
            } else {
                this.jtxpFuncion.setText(this.jtxpFuncion.getText().substring(0, this.jtxpFuncion.getText().indexOf("(")).concat("(").concat(this.jtxpFuncion.getText().substring(this.jtxpFuncion.getText().indexOf("("), this.jtxpFuncion.getCaretPosition())).concat(")").concat("/()").concat(sel2));
                this.jtxpFuncion.grabFocus();
                this.jtxpFuncion.setCaretPosition(sel.length() + 4);
            }
        }
    }

    private void LeerDiferencial() {
        int Diferencial = 0;
        do {
            dato = JOptionPane.showInputDialog(this, "Introduce el Diferencial (una letra)", "Diferencial: ", 2);
            if (dato != null) {
                if (dato.substring(0, 1).toUpperCase().hashCode() > 90 || dato.substring(0, 1).toUpperCase().hashCode() < 65) {
                    JOptionPane.showMessageDialog(this, "Para poder admitirse como diferencial es necesario que sea una letra. \n Revise su función e intente de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                    Diferencial = 0;
                } else {
                    Diferencial = 1;
                }
            }
        } while (Diferencial != 1);
    }

    private void GuardarHistorial() {
        ArrayList his = new ArrayList();
        his.add(this.jtxpFuncion.getText());
        his.add("&&&");
        his.add(this.jtxpProcedimiento.getText());
        his.add("$$$");
        his.add(this.jtxpResultado.getText());
        his.add("%%%");
        CDI.Comentario.stream().forEach((Comentario) -> {
            his.add(Comentario);
        });
        Historial[cont] = his;
        if (cont == 0) {
            Historial[9].clear();
            for (int i = 9; i > 0; i--) {
                Historial[i - 1] = Historial[i];
            }
        } else {
            cont--;
        }
    }

    public void CentrarVentana(JDialog dialogos) {
        dialogos.setSize(520, 320);

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = dialogos.getSize(), dm = new Dimension();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }

        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        dm = dialogos.getSize();
        dialogos.setVisible(true);
        dialogos.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new GUI().setVisible(true);
        }
    }

}
